<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('shareholders')->insert([
            [
                'name' => 'Mwombeki - Kisesa',
                'email' => 'mwombeki@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Wateja Chombos Electrical',
                'email' => 'wchombos@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Wateja Ticha Solar',
                'email' => 'wticha@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Wateja Idrissah Electrical',
                'email' => 'widris@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Rhoda Kitoto',
                'email' => 'rhoda@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Weto Solar',
                'email' => 'weto@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Peter Tarime',
                'email' => 'peter@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mang\'am',
                'email' => 'mangam@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Victor',
                'email' => 'victor@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mama Kanza',
                'email' => 'mkanza@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mama Yuu',
                'email' => 'myuu@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Ernest',
                'email' => 'ernest@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Boss Martin',
                'email' => 'martine@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Unkown Shop',
                'email' => 'unkown@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Jackson',
                'email' => 'jackson@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Godfrey',
                'email' => 'godfrey@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Nicholous',
                'email' => 'nicholous@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Irene',
                'email' => 'irene@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Yasintah - Maduka 9',
                'email' => 'yasinta@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mama Dee - Mabotto Plaza',
                'email' => 'mdee@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mama Mchuma',
                'email' => 'mmchuma@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Baraka',
                'email' => 'baraka@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Wateja Juma Shop',
                'email' => 'wjshop@kanza.com',
                'phone' => '(+255) 228-096-234',
                'location' => 'Musoma - Mara',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '5',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
