<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name'      => 'Africab 2 Way PVC Main Switch',
                'product_key'       => 'A2PMS',
                'product_desc'      => 'main switch njia mbili plastic',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 3 Way PVC Main Switch',
                'product_key'       => 'A3PMS',
                'product_desc'      => 'main switch njia tatu plastic',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 4 Way PVC Main Switch',
                'product_key'       => 'A4PMS',
                'product_desc'      => 'main switch njia nne plastic',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 4 Way Metalic Main Switch',
                'product_key'       => 'A4MMS',
                'product_desc'      => 'main switch njia nne chuma',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 6 Way Metalic Main Switch',
                'product_key'       => 'A6MMS',
                'product_desc'      => 'main switch njia sita chuma',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 1gang 1way Switch',
                'product_key'       => 'A1G1W',
                'product_desc'      => 'switch njia moja africa',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 1gang 2way Switch',
                'product_key'       => 'A1G2W',
                'product_desc'      => 'switch njia moja africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 2gang 1way Switch',
                'product_key'       => 'A2G1W',
                'product_desc'      => 'switch njia mbili africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 2gang 2way Switch',
                'product_key'       => 'A2G2W',
                'product_desc'      => 'switch njia mbili africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 3gang 1way Switch',
                'product_key'       => 'A3G1W',
                'product_desc'      => 'switch njia tatu africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 3gang 2way Switch',
                'product_key'       => 'A3G2W',
                'product_desc'      => 'switch njia tatu africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 4gang 2way Switch',
                'product_key'       => 'A4G2W',
                'product_desc'      => 'switch njia nne africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Switch Socket Single',
                'product_key'       => 'ASSS',
                'product_desc'      => 'Socket njia moja africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Switch Socket Double',
                'product_key'       => 'ASSD',
                'product_desc'      => 'Socket njia mbili africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 20A DP',
                'product_key'       => 'A20A',
                'product_desc'      => 'DP Switch 20A africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 45A DP',
                'product_key'       => 'A45A',
                'product_desc'      => 'DP Switch 45A africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Holder Kubwa Angle',
                'product_key'       => 'AHKA',
                'product_desc'      => 'Holder Kubwa Angle africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Single Metal Box',
                'product_key'       => 'ASMB',
                'product_desc'      => 'Box Chuma Single africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Double Metal Box',
                'product_key'       => 'ASMB',
                'product_desc'      => 'Box Chuma Double africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Max Circuit Breaker',
                'product_key'       => 'AMCB',
                'product_desc'      => 'Circuit Breaker No 1 africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab Conduit Pipes Nzito 3/4"',
                'product_key'       => 'AC3Q',
                'product_desc'      => 'Conduit Pipes Nzito No 1 africab',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Liper Conduit Pipes Nyepesi 3/4"',
                'product_key'       => 'LC3Q',
                'product_desc'      => 'Conduit Pipes Nyepesi No 2 africab',
                'brand_id'          => '4',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 4 Way Metalic Main Switch',
                'product_key'       => 'T4MMS',
                'product_desc'      => 'main switch njia nne chuma',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 6 Way Metalic Main Switch',
                'product_key'       => 'T6MMS',
                'product_desc'      => 'main switch njia sita chuma',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 8 Way Metalic Main Switch',
                'product_key'       => 'T8MMS',
                'product_desc'      => 'main switch njia sita chuma',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic Max Circuit Breaker',
                'product_key'       => 'TMCB',
                'product_desc'      => 'Circuit Breaker No 1 Tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Rsuk Copy Circuit Breaker',
                'product_key'       => 'RCCB',
                'product_desc'      => 'Circuit Breaker No 2 Africable',
                'brand_id'          => '2',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 1.5mm Twin Wire',
                'product_key'       => 'K1.5T',
                'product_desc'      => 'Two in One 1.5mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 2.5mm Twin Wire',
                'product_key'       => 'K2.5T',
                'product_desc'      => 'Two in One 2.5mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 4.0mm Twin Wire',
                'product_key'       => 'K4.0T',
                'product_desc'      => 'Two in One 4.0mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 6.0mm Twin Wire',
                'product_key'       => 'K6.0T',
                'product_desc'      => 'Two in One 6.0mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 1.5mm Single Core',
                'product_key'       => 'K1.5S',
                'product_desc'      => 'Single One 1.5mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 2.5mm Single Core',
                'product_key'       => 'K2.5S',
                'product_desc'      => 'Single 2.5mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 4.0mm Single Core',
                'product_key'       => 'K4.0S',
                'product_desc'      => 'Single 4.0mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Kilimanjaro 6.0mm Single Core',
                'product_key'       => 'K6.0S',
                'product_desc'      => 'Single 6.0mm Cable',
                'brand_id'          => '3',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 1gang 1way Switch',
                'product_key'       => 'T1G1W',
                'product_desc'      => 'switch njia moja tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 1gang 2way Switch',
                'product_key'       => 'T1G2W',
                'product_desc'      => 'switch njia moja tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 2gang 1way Switch',
                'product_key'       => 'T2G1W',
                'product_desc'      => 'switch njia mbili tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 2gang 2way Switch',
                'product_key'       => 'T2G2W',
                'product_desc'      => 'switch njia mbili tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 3gang 1way Switch',
                'product_key'       => 'T3G1W',
                'product_desc'      => 'switch njia tatu tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 3gang 2way Switch',
                'product_key'       => 'T3G2W',
                'product_desc'      => 'switch njia tatu tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 4gang 2way Switch',
                'product_key'       => 'T4G2W',
                'product_desc'      => 'switch njia nne tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic Switch Socket Single',
                'product_key'       => 'TSSS',
                'product_desc'      => 'Socket njia moja tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic Switch Socket Double',
                'product_key'       => 'TSSD',
                'product_desc'      => 'Socket njia mbili tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 20A DP',
                'product_key'       => 'T20A',
                'product_desc'      => 'DP Switch 20A tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic 45A DP',
                'product_key'       => 'T45A',
                'product_desc'      => 'DP Switch 45A tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 1gang 1way Switch',
                'product_key'       => 'H1G1W',
                'product_desc'      => 'switch njia moja hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 1gang 2way Switch',
                'product_key'       => 'H1G2W',
                'product_desc'      => 'switch njia moja hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 2gang 1way Switch',
                'product_key'       => 'H2G1W',
                'product_desc'      => 'switch njia mbili hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 2gang 2way Switch',
                'product_key'       => 'H2G2W',
                'product_desc'      => 'switch njia mbili hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 3gang 1way Switch',
                'product_key'       => 'H3G1W',
                'product_desc'      => 'switch njia tatu hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 3gang 2way Switch',
                'product_key'       => 'H3G2W',
                'product_desc'      => 'switch njia tatu hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo Switch Socket Single',
                'product_key'       => 'HSSS',
                'product_desc'      => 'Socket njia moja hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo Switch Socket Double',
                'product_key'       => 'HSSD',
                'product_desc'      => 'Socket njia mbili hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Hippo 3leg Top Plugs',
                'product_key'       => 'H3LT',
                'product_desc'      => 'Top plugs miguu mitatu hippo',
                'brand_id'          => '12',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tan-Uk Conduit Pipes Nyepesi 3/4"',
                'product_key'       => 'TC3Q',
                'product_desc'      => 'Conduit Pipes Nyepesi No 2 MCL',
                'brand_id'          => '14',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Flexible Wire Kioo',
                'product_key'       => 'SFWK',
                'product_desc'      => 'Flexible Simba na yanga Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Flexible Wire Carrot',
                'product_key'       => 'SFWC',
                'product_desc'      => 'Flexible Wire Carrot Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Holder Ndogo Straight',
                'product_key'       => 'SHNS',
                'product_desc'      => 'Holder Ndogo Straight Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Holder Ndogo Angle',
                'product_key'       => 'SHNA',
                'product_desc'      => 'Holder Ndogo Angle Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Holder Kubwa Straight',
                'product_key'       => 'SHKS',
                'product_desc'      => 'Holder Ndogo Straight Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Holder Kubwa Angle',
                'product_key'       => 'SHKA',
                'product_desc'      => 'Holder Ndogo Angle Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Ailyons Holder Kubwa Straight',
                'product_key'       => 'ALKS',
                'product_desc'      => 'Holder Ndogo Straight Sephlighty',
                'brand_id'          => '9',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Ailyons Holder Kubwa Angle',
                'product_key'       => 'ALKA',
                'product_desc'      => 'Holder Ndogo Angle Sephlighty',
                'brand_id'          => '9',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W3 Pin',
                'product_key'       => 'VW3P',
                'product_desc'      => '3W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W5 Pin',
                'product_key'       => 'VW5P',
                'product_desc'      => '5W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W7 Pin',
                'product_key'       => 'VW7P',
                'product_desc'      => '7W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W10 Pin',
                'product_key'       => 'VW10',
                'product_desc'      => '10W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W12 Pin',
                'product_key'       => 'VW12',
                'product_desc'      => '12W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W15 Pin',
                'product_key'       => 'VW15',
                'product_desc'      => '15W Pin Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W3 Trade',
                'product_key'       => 'VW3T',
                'product_desc'      => '3W Trade Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W5 Trade',
                'product_key'       => 'VW5T',
                'product_desc'      => '5W Trade Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Vallight Bulbs W7 Trade',
                'product_key'       => 'VW7T',
                'product_desc'      => '7W Trade Bulb Vallight',
                'brand_id'          => '6',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W3 Pin',
                'product_key'       => 'TW3P',
                'product_desc'      => '3W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W5 Pin',
                'product_key'       => 'TW5P',
                'product_desc'      => '5W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W7 Pin',
                'product_key'       => 'TW7P',
                'product_desc'      => '7W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W9 Pin',
                'product_key'       => 'TW9P',
                'product_desc'      => '9W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W12 Pin',
                'product_key'       => 'TW12',
                'product_desc'      => '12W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W15 Pin',
                'product_key'       => 'TW15',
                'product_desc'      => '15W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W20 Pin',
                'product_key'       => 'TW20',
                'product_desc'      => '20W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Torch Bulbs W25 Pin',
                'product_key'       => 'TW25',
                'product_desc'      => '25W Pin Bulb Torch',
                'brand_id'          => '11',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Eco 4way Round Box White',
                'product_key'       => 'ERBW',
                'product_desc'      => '4way Round Box White Africab No 2',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africab 4way Round Box White',
                'product_key'       => 'ARBW',
                'product_desc'      => '4way Round Box White Africab No 1',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Eco 4way Round Box Black',
                'product_key'       => 'ERBB',
                'product_desc'      => '4way Round Box Black Africab No 2',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic Single TV Socket',
                'product_key'       => 'TSTS',
                'product_desc'      => 'Tv socket njia moja Tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'KLIK Round Cover White',
                'product_key'       => 'KRCW',
                'product_desc'      => 'Tv socket njia moja Tronic',
                'brand_id'          => '7',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Ailyons 4way Extension',
                'product_key'       => 'A4WE',
                'product_desc'      => 'Extension njia nne Ailyons',
                'brand_id'          => '9',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighy RGB Adapter',
                'product_key'       => 'SRAS',
                'product_desc'      => 'RGB Adapte Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africable Ceiling Fan 14"',
                'product_key'       => 'ASFK',
                'product_desc'      => 'Ceiling Fan pembe nne Africable',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africable Ceiling Fan LED"',
                'product_key'       => 'ASFL',
                'product_desc'      => 'Ceiling Fan yenye taa Africable',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Tronic Black Insulation Tape',
                'product_key'       => 'TBIT',
                'product_desc'      => 'Black Insulation Tape Tronic',
                'brand_id'          => '5',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Africable Black Insulation Tape',
                'product_key'       => 'ABIT',
                'product_desc'      => 'Black Insulation Tape Africable',
                'brand_id'          => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Black Insulation Tape',
                'product_key'       => 'SBIT',
                'product_desc'      => 'Black Insulation Tape Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Straight Black ConeShaped GateLight',
                'product_key'       => 'SBCG',
                'product_desc'      => 'Straight Black ConeShaped GateLight',
                'brand_id'          => '15',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Euroclips 9MM White',
                'product_key'       => 'SE9M',
                'product_desc'      => 'White 9MM Euroclips Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Euroclips 22MM White',
                'product_key'       => 'SE22',
                'product_desc'      => 'White 22MM Euroclips Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty EarthRod Pure Copper',
                'product_key'       => 'SEPC',
                'product_desc'      => 'Pure Copper EarthRod Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty EarthRod Copper II',
                'product_key'       => 'SEC2',
                'product_desc'      => 'Copper II EarthRod Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty EarthRod Ndogo 8mm',
                'product_key'       => 'SEN8',
                'product_desc'      => '8mm EarthRod Ndogo Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty EarthRod Kati 12mm',
                'product_key'       => 'SE12',
                'product_desc'      => '12mm EarthRod Ndogo Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty EarthRod Kubwa 14mm',
                'product_key'       => 'SE14',
                'product_desc'      => '14mm EarthRod Ndogo Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W5 pin',
                'product_key'       => 'SW5P',
                'product_desc'      => 'Bulbs 5W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W7 pin',
                'product_key'       => 'SW7P',
                'product_desc'      => 'Bulbs 7W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W15 pin',
                'product_key'       => 'SW15',
                'product_desc'      => 'Bulbs 15W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W18 pin',
                'product_key'       => 'SW18',
                'product_desc'      => 'Bulbs 18W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W28 pin',
                'product_key'       => 'SW28',
                'product_desc'      => 'Bulbs 28W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W38 pin',
                'product_key'       => 'SW38',
                'product_desc'      => 'Bulbs 38W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_name'      => 'Sephlighty Bulbs W48 pin',
                'product_key'       => 'SW48',
                'product_desc'      => 'Bulbs 48W pin Sephlighty',
                'brand_id'          => '8',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
