<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class SellingPricesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('selling_prices')->insert([
            [
                'product_id'        => '1',
                'min_qty'           => '1',
                'selling_price'     => '25000',
                'shop_price'        => '22000',
                'shop_qty'          => '1',
                'caton_price'        => '21000',
                'caton_qty'          => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '2',
                'min_qty'           => '1',
                'selling_price'     => '28000',
                'shop_price'        => '26000',
                'shop_qty'          => '1',
                'caton_price'       => '25000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '3',
                'min_qty'           => '1',
                'selling_price'     => '30000',
                'shop_price'        => '28000',
                'shop_qty'          => '1',
                'caton_price'       => '27000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '4',
                'min_qty'           => '1',
                'selling_price'     => '65000',
                'shop_price'        => '62000',
                'shop_qty'          => '1',
                'caton_price'       => '60000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '5',
                'min_qty'           => '1',
                'selling_price'     => '75000',
                'shop_price'        => '72000',
                'shop_qty'          => '1',
                'caton_price'       => '70000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '6',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1000',
                'shop_qty'          => '10',
                'caton_price'       => '900',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '7',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1200',
                'shop_qty'          => '10',
                'caton_price'       => '1100',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '8',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'       => '1400',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '9',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'       => '1600',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '10',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2000',
                'shop_qty'          => '10',
                'caton_price'       => '1800',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '11',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2200',
                'shop_qty'          => '10',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '12',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3500',
                'shop_qty'          => '10',
                'caton_price'       => '3200',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '13',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'       => '1650',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '14',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3400',
                'shop_qty'          => '5',
                'caton_price'       => '3300',
                'caton_qty'         => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '15',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '3500',
                'shop_qty'          => '10',
                'caton_price'       => '3200',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '16',
                'min_qty'           => '1',
                'selling_price'     => '7000',
                'shop_price'        => '5500',
                'shop_qty'          => '8',
                'caton_price'       => '5200',
                'caton_qty'         => '80',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '17',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '900',
                'shop_qty'          => '10',
                'caton_price'       => '850',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '18',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1300',
                'shop_qty'          => '10',
                'caton_price'       => '1300',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '19',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '2000',
                'shop_qty'          => '5',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '20',
                'min_qty'           => '1',
                'selling_price'     => '30000',
                'shop_price'        => '27000',
                'shop_qty'          => '1',
                'caton_price'       => '26000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '21',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1700',
                'shop_qty'          => '50',
                'caton_price'       => '1640',
                'caton_qty'         => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '22',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '900',
                'shop_qty'          => '50',
                'caton_price'       => '840',
                'caton_qty'         => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '23',
                'min_qty'           => '1',
                'selling_price'     => '80000',
                'shop_price'        => '75000',
                'shop_qty'          => '1',
                'caton_price'       => '75000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '24',
                'min_qty'           => '1',
                'selling_price'     => '90000',
                'shop_price'        => '85000',
                'shop_qty'          => '1',
                'caton_price'        => '85000',
                'caton_qty'          => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '25',
                'min_qty'           => '1',
                'selling_price'     => '120000',
                'shop_price'        => '110000',
                'shop_qty'          => '1',
                'caton_price'        => '105000',
                'caton_qty'          => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '26',
                'min_qty'           => '1',
                'selling_price'     => '50000',
                'shop_price'        => '45000',
                'shop_qty'          => '1',
                'caton_price'        => '45000',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '27',
                'min_qty'           => '1',
                'selling_price'     => '15000',
                'shop_price'        => '9000',
                'shop_qty'          => '1',
                'caton_price'        => '8500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '28',
                'min_qty'           => '1',
                'selling_price'     => '1800',
                'shop_price'        => '1600',
                'shop_qty'          => '100',
                'caton_price'        => '1550',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '29',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2700',
                'shop_qty'          => '100',
                'caton_price'        => '2500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '30',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3700',
                'shop_qty'          => '100',
                'caton_price'        => '3500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '31',
                'min_qty'           => '1',
                'selling_price'     => '6000',
                'shop_price'        => '5500',
                'shop_qty'          => '100',
                'caton_price'        => '5200',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '32',
                'min_qty'           => '1',
                'selling_price'     => '800',
                'shop_price'        => '600',
                'shop_qty'          => '100',
                'caton_price'        => '550',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '33',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '900',
                'shop_qty'          => '100',
                'caton_price'        => '870',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '34',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1800',
                'shop_qty'          => '100',
                'caton_price'        => '1500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '35',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2500',
                'shop_qty'          => '100',
                'caton_price'        => '2500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '36',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2500',
                'shop_qty'          => '10',
                'caton_price'        => '2300',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '37',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2500',
                'shop_qty'          => '10',
                'caton_price'        => '2500',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '38',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3500',
                'shop_qty'          => '10',
                'caton_price'        => '3300',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '39',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3500',
                'shop_qty'          => '10',
                'caton_price'        => '3500',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '40',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '5000',
                'shop_qty'          => '10',
                'caton_price'        => '3500',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '41',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '5000',
                'shop_qty'          => '10',
                'caton_price'        => '5000',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '42',
                'min_qty'           => '1',
                'selling_price'     => '8000',
                'shop_price'        => '7500',
                'shop_qty'          => '10',
                'caton_price'        => '7500',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '43',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '4800',
                'shop_qty'          => '10',
                'caton_price'        => '4800',
                'caton_qty'          => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '44',
                'min_qty'           => '1',
                'selling_price'     => '8000',
                'shop_price'        => '7500',
                'shop_qty'          => '5',
                'caton_price'        => '7500',
                'caton_qty'          => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '45',
                'min_qty'           => '1',
                'selling_price'     => '7000',
                'shop_price'        => '6500',
                'shop_qty'          => '10',
                'caton_price'        => '6500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '46',
                'min_qty'           => '1',
                'selling_price'     => '12000',
                'shop_price'        => '11000',
                'shop_qty'          => '10',
                'caton_price'        => '10500',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '47',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1000',
                'shop_qty'          => '10',
                'caton_price'        => '950',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '48',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1200',
                'shop_qty'          => '10',
                'caton_price'        => '1150',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '49',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'        => '1450',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '50',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'        => '1650',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '51',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '2000',
                'shop_qty'          => '10',
                'caton_price'        => '1950',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '52',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '2200',
                'shop_qty'          => '10',
                'caton_price'        => '2150',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '53',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'        => '1650',
                'caton_qty'          => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '54',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3400',
                'shop_qty'          => '5',
                'caton_price'        => '3300',
                'caton_qty'          => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '55',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '1600',
                'shop_qty'          => '10',
                'caton_price'       => '1500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '56',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '900',
                'shop_qty'          => '50',
                'caton_price'       => '840',
                'caton_qty'         => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '57',
                'min_qty'           => '1',
                'selling_price'     => '25000',
                'shop_price'        => '20000',
                'shop_qty'          => '1',
                'caton_price'       => '19000',
                'caton_qty'         => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '58',
                'min_qty'           => '1',
                'selling_price'     => '25000',
                'shop_price'        => '20000',
                'shop_qty'          => '1',
                'caton_price'       => '19000',
                'caton_qty'         => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '59',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '600',
                'shop_qty'          => '10',
                'caton_price'       => '550',
                'caton_qty'         => '300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],[
                'product_id'        => '60',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '600',
                'shop_qty'          => '10',
                'caton_price'       => '550',
                'caton_qty'         => '300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '61',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '900',
                'shop_qty'          => '10',
                'caton_price'       => '850',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '62',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '900',
                'shop_qty'          => '10',
                'caton_price'       => '850',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '63',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '900',
                'shop_qty'          => '10',
                'caton_price'       => '850',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '64',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '900',
                'shop_qty'          => '10',
                'caton_price'       => '850',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '65',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'       => '1500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '66',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'       => '1700',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '67',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2000',
                'shop_qty'          => '10',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '68',
                'min_qty'           => '1',
                'selling_price'     => '3500',
                'shop_price'        => '2500',
                'shop_qty'          => '10',
                'caton_price'       => '2500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '69',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3300',
                'shop_qty'          => '10',
                'caton_price'       => '3200',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '70',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '4000',
                'shop_qty'          => '10',
                'caton_price'       => '4000',
                'caton_qty'         => '600',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '71',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'       => '1500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '72',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'       => '1700',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '73',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2000',
                'shop_qty'          => '10',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '74',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'       => '1500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '75',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '1700',
                'shop_qty'          => '10',
                'caton_price'       => '1700',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '76',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2000',
                'shop_qty'          => '10',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '77',
                'min_qty'           => '1',
                'selling_price'     => '3500',
                'shop_price'        => '2500',
                'shop_qty'          => '10',
                'caton_price'       => '2500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '78',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3500',
                'shop_qty'          => '10',
                'caton_price'       => '3500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '79',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '4000',
                'shop_qty'          => '10',
                'caton_price'       => '4000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '80',
                'min_qty'           => '1',
                'selling_price'     => '7000',
                'shop_price'        => '6500',
                'shop_qty'          => '10',
                'caton_price'       => '6500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '81',
                'min_qty'           => '1',
                'selling_price'     => '10000',
                'shop_price'        => '9000',
                'shop_qty'          => '10',
                'caton_price'       => '9000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '82',
                'min_qty'           => '1',
                'selling_price'     => '500',
                'shop_price'        => '300',
                'shop_qty'          => '150',
                'caton_price'       => '300',
                'caton_qty'         => '150',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '83',
                'min_qty'           => '1',
                'selling_price'     => '500',
                'shop_price'        => '400',
                'shop_qty'          => '200',
                'caton_price'       => '400',
                'caton_qty'         => '200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '84',
                'min_qty'           => '1',
                'selling_price'     => '500',
                'shop_price'        => '250',
                'shop_qty'          => '150',
                'caton_price'       => '250',
                'caton_qty'         => '150',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '85',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '4500',
                'shop_qty'          => '10',
                'caton_price'       => '4500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '86',
                'min_qty'           => '1',
                'selling_price'     => '500',
                'shop_price'        => '300',
                'shop_qty'          => '100',
                'caton_price'       => '300',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '87',
                'min_qty'           => '1',
                'selling_price'     => '8000',
                'shop_price'        => '4500',
                'shop_qty'          => '10',
                'caton_price'       => '4200',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '88',
                'min_qty'           => '1',
                'selling_price'     => '15000',
                'shop_price'        => '12000',
                'shop_qty'          => '10',
                'caton_price'       => '10000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '89',
                'min_qty'           => '1',
                'selling_price'     => '150000',
                'shop_price'        => '140000',
                'shop_qty'          => '1',
                'caton_price'       => '130000',
                'caton_qty'         => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '90',
                'min_qty'           => '1',
                'selling_price'     => '170000',
                'shop_price'        => '160000',
                'shop_qty'          => '1',
                'caton_price'       => '155000',
                'caton_qty'         => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '91',
                'min_qty'           => '1',
                'selling_price'     => '1500',
                'shop_price'        => '1200',
                'shop_qty'          => '10',
                'caton_price'       => '1000',
                'caton_qty'         => '500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '92',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '700',
                'shop_qty'          => '10',
                'caton_price'       => '600',
                'caton_qty'         => '500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '93',
                'min_qty'           => '1',
                'selling_price'     => '1000',
                'shop_price'        => '700',
                'shop_qty'          => '10',
                'caton_price'       => '600',
                'caton_qty'         => '500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '94',
                'min_qty'           => '1',
                'selling_price'     => '20000',
                'shop_price'        => '18000',
                'shop_qty'          => '1',
                'caton_price'       => '17000',
                'caton_qty'         => '10',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '95',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '1',
                'caton_price'       => '1000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '96',
                'min_qty'           => '1',
                'selling_price'     => '5000',
                'shop_price'        => '3500',
                'shop_qty'          => '1',
                'caton_price'       => '3000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '97',
                'min_qty'           => '1',
                'selling_price'     => '45000',
                'shop_price'        => '42000',
                'shop_qty'          => '1',
                'caton_price'       => '42000',
                'caton_qty'         => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '98',
                'min_qty'           => '1',
                'selling_price'     => '15000',
                'shop_price'        => '12000',
                'shop_qty'          => '1',
                'caton_price'       => '12000',
                'caton_qty'         => '1',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '99',
                'maximmum_qty'      => '1',
                'selling_price'     => '5000',
                'shop_price'        => '3000',
                'shop_qty'          => '1',
                'caton_price'       => '2500',
                'caton_qty'         => '50',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '100',
                'min_qty'           => '1',
                'selling_price'     => '8000',
                'shop_price'        => '6000',
                'shop_qty'          => '1',
                'caton_price'       => '6000',
                'caton_qty'         => '25',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '101',
                'min_qty'           => '1',
                'selling_price'     => '10000',
                'shop_price'        => '8000',
                'shop_qty'          => '1',
                'caton_price'       => '7000',
                'caton_qty'         => '20',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '102',
                'min_qty'           => '1',
                'selling_price'     => '2000',
                'shop_price'        => '1500',
                'shop_qty'          => '10',
                'caton_price'       => '1500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '103',
                'min_qty'           => '1',
                'selling_price'     => '2500',
                'shop_price'        => '2000',
                'shop_qty'          => '1',
                'caton_price'       => '2000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '104',
                'min_qty'           => '1',
                'selling_price'     => '3000',
                'shop_price'        => '2500',
                'shop_qty'          => '1',
                'caton_price'       => '2500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '105',
                'min_qty'           => '1',
                'selling_price'     => '4000',
                'shop_price'        => '3500',
                'shop_qty'          => '1',
                'caton_price'       => '3500',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '106',
                'min_qty'           => '1',
                'selling_price'     => '6000',
                'shop_price'        => '5000',
                'shop_qty'          => '1',
                'caton_price'       => '5000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '107',
                'min_qty'           => '1',
                'selling_price'     => '8000',
                'shop_price'        => '7000',
                'shop_qty'          => '1',
                'caton_price'       => '7000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '108',
                'min_qty'           => '1',
                'selling_price'     => '10000',
                'shop_price'        => '9000',
                'shop_qty'          => '1',
                'caton_price'       => '9000',
                'caton_qty'         => '100',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
