<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class SellingPricesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('selling_prices')->insert([
            [
                'product_id'        => '1',
                'maximmum_qty'      => '100',
                'selling_price'     => '22000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '2',
                'maximmum_qty'      => '100',
                'selling_price'     => '26000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '3',
                'maximmum_qty'      => '100',
                'selling_price'     => '28000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '4',
                'maximmum_qty'      => '100',
                'selling_price'     => '60000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '5',
                'maximmum_qty'      => '100',
                'selling_price'     => '70000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '6',
                'maximmum_qty'      => '100',
                'selling_price'     => '1000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '7',
                'maximmum_qty'      => '100',
                'selling_price'     => '1300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '8',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '9',
                'maximmum_qty'      => '100',
                'selling_price'     => '1800',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '10',
                'maximmum_qty'      => '100',
                'selling_price'     => '2000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '11',
                'maximmum_qty'      => '100',
                'selling_price'     => '2200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '12',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '13',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '14',
                'maximmum_qty'      => '100',
                'selling_price'     => '3400',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '15',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '16',
                'maximmum_qty'      => '100',
                'selling_price'     => '6000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '17',
                'maximmum_qty'      => '100',
                'selling_price'     => '1000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '18',
                'maximmum_qty'      => '100',
                'selling_price'     => '1300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '19',
                'maximmum_qty'      => '100',
                'selling_price'     => '2000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '20',
                'maximmum_qty'      => '100',
                'selling_price'     => '27000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '21',
                'maximmum_qty'      => '100',
                'selling_price'     => '1640',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '22',
                'maximmum_qty'      => '100',
                'selling_price'     => '840',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '23',
                'maximmum_qty'      => '100',
                'selling_price'     => '75000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '24',
                'maximmum_qty'      => '100',
                'selling_price'     => '85000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '25',
                'maximmum_qty'      => '100',
                'selling_price'     => '110000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '26',
                'maximmum_qty'      => '100',
                'selling_price'     => '45000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '27',
                'maximmum_qty'      => '100',
                'selling_price'     => '9000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '28',
                'maximmum_qty'      => '100',
                'selling_price'     => '1480',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '29',
                'maximmum_qty'      => '100',
                'selling_price'     => '2400',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '30',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '31',
                'maximmum_qty'      => '100',
                'selling_price'     => '5300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '32',
                'maximmum_qty'      => '100',
                'selling_price'     => '520',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '33',
                'maximmum_qty'      => '100',
                'selling_price'     => '850',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '34',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '35',
                'maximmum_qty'      => '100',
                'selling_price'     => '2500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '36',
                'maximmum_qty'      => '100',
                'selling_price'     => '2500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '37',
                'maximmum_qty'      => '100',
                'selling_price'     => '2800',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '38',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '39',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '40',
                'maximmum_qty'      => '100',
                'selling_price'     => '5000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '41',
                'maximmum_qty'      => '100',
                'selling_price'     => '5000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '42',
                'maximmum_qty'      => '100',
                'selling_price'     => '8000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '43',
                'maximmum_qty'      => '100',
                'selling_price'     => '5000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '44',
                'maximmum_qty'      => '100',
                'selling_price'     => '8000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '45',
                'maximmum_qty'      => '100',
                'selling_price'     => '7000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '46',
                'maximmum_qty'      => '100',
                'selling_price'     => '12000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '47',
                'maximmum_qty'      => '100',
                'selling_price'     => '1000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '48',
                'maximmum_qty'      => '100',
                'selling_price'     => '1200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '49',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '50',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '51',
                'maximmum_qty'      => '100',
                'selling_price'     => '1800',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '52',
                'maximmum_qty'      => '100',
                'selling_price'     => '1900',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '53',
                'maximmum_qty'      => '100',
                'selling_price'     => '1800',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '54',
                'maximmum_qty'      => '100',
                'selling_price'     => '3600',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '55',
                'maximmum_qty'      => '100',
                'selling_price'     => '1600',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '56',
                'maximmum_qty'      => '100',
                'selling_price'     => '800',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '57',
                'maximmum_qty'      => '100',
                'selling_price'     => '19000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '58',
                'maximmum_qty'      => '100',
                'selling_price'     => '19000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '59',
                'maximmum_qty'      => '100',
                'selling_price'     => '600',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],[
                'product_id'        => '60',
                'maximmum_qty'      => '100',
                'selling_price'     => '600',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '61',
                'maximmum_qty'      => '100',
                'selling_price'     => '900',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '62',
                'maximmum_qty'      => '100',
                'selling_price'     => '900',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '63',
                'maximmum_qty'      => '100',
                'selling_price'     => '900',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '64',
                'maximmum_qty'      => '100',
                'selling_price'     => '900',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '65',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '66',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '67',
                'maximmum_qty'      => '100',
                'selling_price'     => '2000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '68',
                'maximmum_qty'      => '100',
                'selling_price'     => '2700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '69',
                'maximmum_qty'      => '100',
                'selling_price'     => '3200',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '70',
                'maximmum_qty'      => '100',
                'selling_price'     => '4000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '71',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '72',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '73',
                'maximmum_qty'      => '100',
                'selling_price'     => '2000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '74',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '75',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '76',
                'maximmum_qty'      => '100',
                'selling_price'     => '2000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '77',
                'maximmum_qty'      => '100',
                'selling_price'     => '2700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '78',
                'maximmum_qty'      => '100',
                'selling_price'     => '3400',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '79',
                'maximmum_qty'      => '100',
                'selling_price'     => '4000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '80',
                'maximmum_qty'      => '100',
                'selling_price'     => '6000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '81',
                'maximmum_qty'      => '100',
                'selling_price'     => '10000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '82',
                'maximmum_qty'      => '100',
                'selling_price'     => '350',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '83',
                'maximmum_qty'      => '100',
                'selling_price'     => '500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '84',
                'maximmum_qty'      => '100',
                'selling_price'     => '300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '85',
                'maximmum_qty'      => '100',
                'selling_price'     => '5000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '86',
                'maximmum_qty'      => '100',
                'selling_price'     => '300',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '87',
                'maximmum_qty'      => '100',
                'selling_price'     => '4500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '88',
                'maximmum_qty'      => '100',
                'selling_price'     => '10000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '89',
                'maximmum_qty'      => '100',
                'selling_price'     => '140000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '90',
                'maximmum_qty'      => '100',
                'selling_price'     => '160000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '91',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '92',
                'maximmum_qty'      => '100',
                'selling_price'     => '1000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '93',
                'maximmum_qty'      => '100',
                'selling_price'     => '1000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '94',
                'maximmum_qty'      => '100',
                'selling_price'     => '17000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '95',
                'maximmum_qty'      => '100',
                'selling_price'     => '1500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '96',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '97',
                'maximmum_qty'      => '100',
                'selling_price'     => '45000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '98',
                'maximmum_qty'      => '100',
                'selling_price'     => '15000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '99',
                'maximmum_qty'      => '100',
                'selling_price'     => '2500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '100',
                'maximmum_qty'      => '100',
                'selling_price'     => '7000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '101',
                'maximmum_qty'      => '100',
                'selling_price'     => '10000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '102',
                'maximmum_qty'      => '100',
                'selling_price'     => '1400',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '103',
                'maximmum_qty'      => '100',
                'selling_price'     => '1700',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '104',
                'maximmum_qty'      => '100',
                'selling_price'     => '2500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '105',
                'maximmum_qty'      => '100',
                'selling_price'     => '3500',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '106',
                'maximmum_qty'      => '100',
                'selling_price'     => '5000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '107',
                'maximmum_qty'      => '100',
                'selling_price'     => '7000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
            [
                'product_id'        => '108',
                'maximmum_qty'      => '100',
                'selling_price'     => '9000',
                'created_at'        => date("Y-m-d H:i:s"),
                'updated_at'        => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
