<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use DB;

class SuppliersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('shareholders')->insert([
            [
                'name' => '7Skies Electricals',
                'email' => 'skies@kanza.com',
                'phone' => '(+255) 228-096-235',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Hilda Vallight',
                'email' => 'hilda@kanza.com',
                'phone' => '(+255) 228-096-236',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Hussein Sephlighty',
                'email' => 'husseinseph@kanza.com',
                'phone' => '(+255) 228-096-237',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Chombos Electrical',
                'email' => 'chombos@kanza.com',
                'phone' => '(+255) 228-096-238',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Ticha Solar',
                'email' => 'ticha@kanza.com',
                'phone' => '(+255) 228-096-239',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Sallehe Torch',
                'email' => 'salehe@kanza.com',
                'phone' => '(+255) 228-096-240',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mustafa Hakmji',
                'email' => 'hakimji@kanza.com',
                'phone' => '(+255) 228-096-241',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Bichakila Electricals',
                'email' => 'bichakila@kanza.com',
                'phone' => '(+255) 228-096-242',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Beitas Electricals',
                'email' => 'bichakila@kanza.com',
                'phone' => '(+255) 228-096-243',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mwanza Lights',
                'email' => 'mlights@kanza.com',
                'phone' => '(+255) 228-096-246',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'AM Electricals',
                'email' => 'am@kanza.com',
                'phone' => '(+255) 228-096-244',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Babuu Electricals',
                'email' => 'bichakila@kanza.com',
                'phone' => '(+255) 228-096-245',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'LightHouse Electricals',
                'email' => 'lhous@kanza.com',
                'phone' => '(+255) 228-096-247',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Paul Tata',
                'email' => 'ptata@kanza.com',
                'phone' => '(+255) 228-096-248',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Mama Shio',
                'email' => 'mshio@kanza.com',
                'phone' => '(+255) 228-096-249',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'name' => 'Idrissah Electricals',
                'email' => 'idris@kanza.com',
                'phone' => '(+255) 228-096-250',
                'location' => 'Mwanza - Tanzania',
                'payement_method' => 'NBC Bank',
                'account_number' => '4567-9545-9856-9876',
                'role' => '6',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ]);
    }
}
